version: '3.4'
name: the-catalyst-dev

services:
  catalyst:
    container_name: catalyst-dev
    networks: 
      - catalyst-dev
    restart: always
    build:
      context: .
      network: host
      dockerfile: Catalyst/Dockerfile
    links:
        - mssql:database

  mssql:
    container_name: catalyst-dev-db
    networks: 
      - catalyst-dev
    restart: always
    build:
      context: .
      network: host
      dockerfile: Catalyst/Redistributables/SQL/Dockerfile
    volumes:
      - data:/mssql/data
      - backup:/mssql/backup
      - log:/mssql/log
      - dump:/mssql/dump
    secrets:
      - sa_password
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD_FILE: /run/secrets/sa_password
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
      MSSQL_BACKUP_DIR: /mssql/backup
      MSSQL_DATA_DIR: /mssql/data
      MSSQL_LOG_DIR: /mssql/log
      MSSQL_DUMP_DIR: /mssql/dump
      MSSQL_MASTER_DATA_FILE: /mssql/data/master.mdf
      MSSQL_MASTER_LOG_FILE: /mssql/log/mastlog.ldf
      MSSQL_ERROR_LOG_FILE: /mssql/log/errorlog
  
volumes:
  data:
  backup:
  log:
  dump:

secrets:
  sa_password:
    file: ./Catalyst/Redistributables/SQL/secrets/sa_password.txt

networks:
  catalyst-dev:
    name: catalyst-dev
    driver: bridge
